from __future__ import annotations

import json
import os
import itertools
import socket
from urllib.parse import urlparse
import urllib.error
import urllib.request
from typing import Any


class BridgeError(RuntimeError):
    """Raised when the 3ds Max bridge cannot complete an operation."""


class MaxBridgeClient:
    """Small JSON-RPC client for the localhost Max bridge.

    The transport is intentionally isolated from MCP tool definitions so the
    bridge can later move from HTTP to named pipes without changing the tools.
    """

    def __init__(self, endpoint: str | None = None, timeout: float = 15.0) -> None:
        self.endpoint = endpoint or os.getenv(
            # 8765 is the documented Autodesk/3ds Max MCP TCP fallback.
            # Set MAX_MCP_BRIDGE_URL to http://127.0.0.1:9766 for the bundled
            # HTTP bridge in bridge/max_mcp_bridge.ms.
            "MAX_MCP_BRIDGE_URL", "tcp://127.0.0.1:8765"
        )
        self.timeout = max(0.5, float(timeout))
        self.max_response_bytes = 4 * 1024 * 1024
        self.token = os.getenv("MAX_MCP_TOKEN", "")
        self._request_ids = itertools.count(1)

    def call(self, method: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
        scheme = urlparse(self.endpoint).scheme.lower()
        if scheme in {"tcp", "legacy"}:
            return self._call_legacy(method, params)
        return self._call_http(method, params)

    def _call_http(self, method: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
        payload = json.dumps(
            {
                "jsonrpc": "2.0",
                "id": next(self._request_ids),
                "method": method,
                "params": params or {},
            },
            separators=(",", ":"),
        ).encode("utf-8")
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        if self.token:
            headers["X-MCP-Token"] = self.token
        request = urllib.request.Request(
            self.endpoint,
            data=payload,
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                body = json.loads(response.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            raise BridgeError(
                "3ds Max bridge is unavailable. Start the bridge inside 3ds Max "
                f"and check {self.endpoint}."
            ) from exc

        if body.get("jsonrpc") != "2.0":
            raise BridgeError("Bridge returned a non-JSON-RPC response.")
        if "error" in body:
            error = body["error"]
            if isinstance(error, dict):
                raise BridgeError(
                    f"{error.get('code', 'bridge_error')}: "
                    f"{error.get('message', 'Unknown bridge error')}"
                )
            raise BridgeError(str(error))
        result = body.get("result")
        if not isinstance(result, dict):
            raise BridgeError("Bridge returned an invalid result envelope.")
        return result

    def _call_legacy(self, method: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
        """Call the MaxScript TCP fallback shipped by existing Max installs.

        The legacy server accepts one JSON line with a MaxScript command and
        returns a JSON envelope whose ``result`` field is a string. This path
        is intentionally restricted to commands generated by this module.
        """
        parsed = urlparse(self.endpoint)
        host = parsed.hostname or "127.0.0.1"
        port = parsed.port or 8765
        command = _legacy_command(method, params or {})
        request_id = str(next(self._request_ids))
        request = json.dumps(
            {
                "type": "maxscript",
                "requestId": request_id,
                "command": command,
            },
            separators=(",", ":"),
        ).encode("utf-8") + b"\n"
        try:
            with socket.create_connection((host, port), timeout=self.timeout) as client:
                client.sendall(request)
                client.settimeout(self.timeout)
                chunks: list[bytes] = []
                while True:
                    chunk = client.recv(65536)
                    if not chunk:
                        break
                    chunks.append(chunk)
                    if sum(len(part) for part in chunks) > self.max_response_bytes:
                        raise BridgeError("Legacy bridge response exceeded 4 MiB.")
                    if b"\n" in chunk:
                        break
        except OSError as exc:
            raise BridgeError(
                f"Legacy 3ds Max MCP TCP bridge is unavailable at {host}:{port}."
            ) from exc

        try:
            envelope = json.loads(b"".join(chunks).decode("utf-8").strip())
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise BridgeError("Legacy bridge returned invalid JSON.") from exc
        if not envelope.get("success", False):
            raise BridgeError(envelope.get("error") or "Legacy bridge command failed.")
        result = envelope.get("result", "")
        if isinstance(result, str):
            try:
                result = json.loads(result)
            except json.JSONDecodeError:
                return {"ok": True, "value": result, "legacy": True}
        if isinstance(result, dict):
            result.setdefault("legacy", True)
            return result
        return {"ok": True, "value": result, "legacy": True}


def _ms_string(value: str) -> str:
    """Quote a Python string as a MaxScript string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _legacy_command(method: str, params: dict[str, Any]) -> str:
    """Generate a small, deterministic MaxScript command for the fallback."""
    if method == "host.status":
        return "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; local h=dotNetObject \"System.Collections.Hashtable\"; h.Add \"ok\" true; h.Add \"transport\" \"native_tcp\"; h.Add \"max_version\" ((maxVersion())[1] as string); h.Add \"object_count\" objects.count; h.Add \"selection_count\" selection.count; h.Add \"capabilities\" #(\"host.status\", \"scene.summary\", \"scene.verify\", \"object.create_box\", \"object.create_cylinder\", \"object.create_mesh\", \"object.transform\", \"object.delete\"); j.SerializeObject h)"
    if method == "scene.summary":
        return "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; local h=dotNetObject \"System.Collections.Hashtable\"; h.Add \"ok\" true; h.Add \"object_count\" objects.count; h.Add \"geometry_count\" geometry.count; h.Add \"selection\" (for n in selection collect n.name); h.Add \"names\" (for n in geometry collect n.name); j.SerializeObject h)"
    if method == "scene.verify":
        return "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; local h=dotNetObject \"System.Collections.Hashtable\"; h.Add \"ok\" true; h.Add \"object_count\" objects.count; h.Add \"geometry_count\" geometry.count; j.SerializeObject h)"
    if method == "object.create_box":
        name = _ms_string(str(params.get("name", "MCP_Box")))
        width = float(params.get("width", 100.0))
        length = float(params.get("length", 100.0))
        height = float(params.get("height", 100.0))
        position = params.get("position", [0.0, 0.0, 0.0])
        x, y, z = (float(position[i]) for i in range(3))
        dry_run = "true" if params.get("dry_run", False) else "false"
        return (
            "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; "
            "local h=dotNetObject \"System.Collections.Hashtable\"; "
            f"local name={name}; local dry={dry_run}; local n=undefined; "
            "if dry then (h.Add \"ok\" true; h.Add \"dry_run\" true) "
            f"else (if (getNodeByName name exact:true)!=undefined then (h.Add \"ok\" false; h.Add \"error\" \"name_conflict\") else (undo \"MCP create box\" on (n=box name:name width:{width} length:{length} height:{height} pos:(point3 {x} {y} {z})); h.Add \"ok\" true; h.Add \"name\" name; h.Add \"handle\" ((getHandleByAnim n) as string); h.Add \"class\" ((classOf n) as string); h.Add \"position\" #(n.position.x,n.position.y,n.position.z); h.Add \"dimensions\" #({width},{length},{height}))); "
            "j.SerializeObject h)"
        )
    if method == "object.transform":
        name = _ms_string(str(params.get("name", "")))
        position = params.get("position")
        rotation = params.get("rotation_degrees")
        assignments: list[str] = []
        if position is not None:
            for index, axis in enumerate(("x", "y", "z")):
                if position[index] is not None:
                    assignments.append(f"n.position.{axis}={float(position[index])}")
        if rotation is not None:
            values = [
                str(float(value)) if value is not None else f"((n.rotation as eulerangles).{axis})"
                for value, axis in zip(rotation, ("x", "y", "z"))
            ]
            assignments.append(f"n.rotation=eulerangles {values[0]} {values[1]} {values[2]}")
        if not assignments:
            raise BridgeError("object.transform requires position or rotation_degrees.")
        return (
            "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; "
            "local h=dotNetObject \"System.Collections.Hashtable\"; "
            f"local n=getNodeByName {name} exact:true; "
            f"if n==undefined then (h.Add \"ok\" false; h.Add \"error\" \"not_found\") else (undo \"MCP transform object\" on ({';'.join(assignments)}); local r=n.rotation as eulerangles; h.Add \"ok\" true; h.Add \"name\" n.name; h.Add \"handle\" ((getHandleByAnim n) as string); h.Add \"position\" #(n.position.x,n.position.y,n.position.z); h.Add \"rotation_degrees\" #(r.x,r.y,r.z)); "
            "j.SerializeObject h)"
        )
    if method == "object.create_mesh":
        name = _ms_string(str(params.get("name", "MCP_Mesh")))
        vertices = params.get("vertices", [])
        faces = params.get("faces", [])
        if len(vertices) < 3 or not faces:
            raise BridgeError("object.create_mesh requires at least three vertices and one face.")
        if any(len(vertex) != 3 for vertex in vertices) or any(len(face) != 3 for face in faces):
            raise BridgeError("object.create_mesh accepts three-component vertices and triangular faces.")
        vertex_count = len(vertices)
        if any(index < 1 or index > vertex_count for face in faces for index in face):
            raise BridgeError("object.create_mesh face indices must be 1-based vertex indices.")
        vertex_literal = "#(" + ",".join(
            f"(point3 {float(vertex[0])} {float(vertex[1])} {float(vertex[2])})"
            for vertex in vertices
        ) + ")"
        face_literal = "#(" + ",".join(
            f"(point3 {int(face[0])} {int(face[1])} {int(face[2])})" for face in faces
        ) + ")"
        position = params.get("position", [0.0, 0.0, 0.0])
        x, y, z = (float(position[i]) for i in range(3))
        dry_run = "true" if params.get("dry_run", False) else "false"
        return (
            "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; "
            "local h=dotNetObject \"System.Collections.Hashtable\"; "
            f"local name={name}; local dry={dry_run}; local verts={vertex_literal}; local faces={face_literal}; local n=undefined; "
            "if dry then (h.Add \"ok\" true; h.Add \"dry_run\" true; h.Add \"vertex_count\" verts.count; h.Add \"face_count\" faces.count) "
            f"else (if (getNodeByName name exact:true)!=undefined then (h.Add \"ok\" false; h.Add \"error\" \"name_conflict\") else (undo \"MCP create mesh\" on (n=mesh name:name vertices:verts faces:faces; n.position=(point3 {x} {y} {z}); update n); h.Add \"ok\" true; h.Add \"name\" name; h.Add \"handle\" ((getHandleByAnim n) as string); h.Add \"class\" ((classOf n) as string); h.Add \"vertex_count\" verts.count; h.Add \"face_count\" faces.count; h.Add \"position\" #(n.position.x,n.position.y,n.position.z))); "
            "j.SerializeObject h)"
        )
    if method == "object.create_cylinder":
        name = _ms_string(str(params.get("name", "MCP_Cylinder")))
        radius = float(params.get("radius", 50.0))
        height = float(params.get("height", 100.0))
        segments = int(params.get("segments", 32))
        position = params.get("position", [0.0, 0.0, 0.0])
        x, y, z = (float(position[i]) for i in range(3))
        dry_run = "true" if params.get("dry_run", False) else "false"
        return (
            "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; "
            "local h=dotNetObject \"System.Collections.Hashtable\"; "
            f"local name={name}; local dry={dry_run}; local n=undefined; "
            "if dry then (h.Add \"ok\" true; h.Add \"dry_run\" true) "
            f"else (if (getNodeByName name exact:true)!=undefined then (h.Add \"ok\" false; h.Add \"error\" \"name_conflict\") else (undo \"MCP create cylinder\" on (n=cylinder name:name radius:{radius} height:{height} sides:{segments} pos:(point3 {x} {y} {z})); h.Add \"ok\" true; h.Add \"name\" name; h.Add \"handle\" ((getHandleByAnim n) as string); h.Add \"class\" ((classOf n) as string); h.Add \"position\" #(n.position.x,n.position.y,n.position.z); h.Add \"radius\" {radius}; h.Add \"height\" {height}; h.Add \"segments\" {segments})); "
            "j.SerializeObject h)"
        )
    if method == "object.delete":
        name = _ms_string(str(params.get("name", "")))
        return (
            "(local j=dotNetClass \"Newtonsoft.Json.JsonConvert\"; "
            "local h=dotNetObject \"System.Collections.Hashtable\"; "
            f"local n=getNodeByName {name} exact:true; "
            "if n==undefined then (h.Add \"ok\" false; h.Add \"error\" \"not_found\") else (local handle=((getHandleByAnim n) as string); undo \"MCP delete object\" on (delete n); h.Add \"ok\" true; h.Add \"name\" " + name + "; h.Add \"handle\" handle); "
            "j.SerializeObject h)"
        )
    raise BridgeError(f"Unsupported legacy method: {method}")
